In [1]:
import copy
import datetime as dt
from datetime import datetime
import importlib  # needed so that we can reload packages
import logging
import os
import pathlib
import sys
import time
import warnings
from typing import Union, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from utils.logger_utils import setup_clean_logger, mute_external_loggers

# SISEPUEDE imports
from sisepuede.manager.sisepuede_examples import SISEPUEDEExamples
from sisepuede.manager.sisepuede_file_structure import SISEPUEDEFileStructure
import sisepuede.core.support_classes as sc
import sisepuede.transformers as trf
import sisepuede.utilities._plotting as spu
import sisepuede.utilities._toolbox as sf
import sisepuede.core.attribute_table as att
import sisepuede.manager.sisepuede_examples as sxl
import sisepuede.manager.sisepuede_file_structure as sfs
import sisepuede.manager.sisepuede_models as sm
import sisepuede.visualization.plots as svp

# --- Runtime configuration ---
warnings.filterwarnings("ignore")

# Set up a clean logger for your notebook
logger = setup_clean_logger("notebook", logging.INFO)
logger.info("Notebook started successfully.")

# Mute logs from sisepuede to avoid duplication
mute_external_loggers(["sisepuede"])

/Users/fabianfuentes/anaconda3/envs/ssp_MEX/lib/python3.11/site-packages/munch/__init__.py:24: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
2026-01-17 14:31:59,305 - INFO - Notebook started successfully.

In [2]:
%load_ext autoreload
%autoreload 2

### Initial Set up

Make sure to edit the config yaml under ssp_modeling/config_files/config.yaml

You can also create a new config yaml

In [3]:
# Set up dir paths

CURR_DIR_PATH = pathlib.Path(os.getcwd())
SSP_MODELING_DIR_PATH = CURR_DIR_PATH.parent
PROJECT_DIR_PATH = SSP_MODELING_DIR_PATH.parent
DATA_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("input_data")
RUN_OUTPUT_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("ssp_run_output")
SCENARIO_MAPPING_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("scenario_mapping")
CONFIG_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("config_files")
TRANSFORMATIONS_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("transformations")
MISC_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("misc")
STRATEGIES_DEFINITIONS_FILE_PATH = TRANSFORMATIONS_DIR_PATH.joinpath("strategy_definitions.csv")
STRATEGY_MAPPING_FILE_PATH = MISC_DIR_PATH.joinpath("strategy_mapping.yaml")

In [4]:
from ssp_transformations_handler.GeneralUtils import GeneralUtils
from ssp_transformations_handler.TransformationUtils import TransformationYamlProcessor, StrategyCSVHandler

# Initialize general utilities
g_utils = GeneralUtils()

In [5]:
# Load config file, double check your parameters are correct

YAML_FILE_PATH = os.path.join(CONFIG_DIR_PATH, "config.yaml")
config_params = g_utils.read_yaml(YAML_FILE_PATH)

country_name = config_params['country_name']
ssp_input_file_name = config_params['ssp_input_file_name']
ssp_transformation_cw = config_params['ssp_transformation_cw']
energy_model_flag = config_params['energy_model_flag']
set_lndu_reallocation_factor_to_zero_flag = config_params['set_lndu_reallocation_factor_to_zero']

# Print config parameters
logger.info(f"Country name: {country_name}")
logger.info(f"SSP input file name: {ssp_input_file_name}")
logger.info(f"SSP transformation CW: {ssp_transformation_cw}")
logger.info(f"Energy model flag: {energy_model_flag}")
logger.info(f"Set lndu reallocation factor to zero flag: {set_lndu_reallocation_factor_to_zero_flag}")

2026-01-17 14:31:59,412 - INFO - Country name: mexico
2026-01-17 14:31:59,413 - INFO - SSP input file name: sisepuede_raw_inputs_MEX_251209.csv
2026-01-17 14:31:59,413 - INFO - SSP transformation CW: ssp_mexico_transformation_strategy.xlsx
2026-01-17 14:31:59,413 - INFO - Energy model flag: True
2026-01-17 14:31:59,413 - INFO - Set lndu reallocation factor to zero flag: True

In [6]:
def get_file_structure(
    y0: int = 2015,
    y1: int = 2060,
) -> Tuple[sfs.SISEPUEDEFileStructure, att.AttributeTable]:
    """Get the SISEPUEDE File Structure and update the attribute table
        with new years.
    """
    # setup some SISEPUEDE variables and update time period
    file_struct = sfs.SISEPUEDEFileStructure(
        initialize_directories = False,
    )
 
    # get some keys
    key_time_period = file_struct.model_attributes.dim_time_period
    key_year = file_struct.model_attributes.field_dim_year
 
 
    ##  BUILD THE ATTRIBUTE AND UPDATE
 
    # setup the new attribute table
    years = np.arange(y0, y1 + 1, ).astype(int)
    attribute_time_period = att.AttributeTable(
        pd.DataFrame(
            {
                key_time_period: range(len(years)),
                key_year: years,
            }
        ),
        key_time_period,
    )
 
    # finally, update the ModelAttributes inside the file structure
    (
        file_struct
        .model_attributes
        .update_dimensional_attribute_table(
            attribute_time_period,
        )
    )
 
    # return the tuple
    out = (file_struct, attribute_time_period, )
 
    return out
 
# # setup models
# models = sm.SISEPUEDEModels(
#     matt,
#     allow_electricity_run = True,
#     fp_julia = _FILE_STRUCTURE.dir_jl,
#     fp_nemomod_reference_files = _FILE_STRUCTURE.dir_ref_nemo,
#     initialize_julia = True, 
# )

In [7]:
# Set up SSP objects
INPUT_FILE_PATH = DATA_DIR_PATH.joinpath(ssp_input_file_name)

# model attributes and associated support classes
_EXAMPLES = sxl.SISEPUEDEExamples()
_FILE_STRUCTURE, _ATTRIBUTE_TABLE_TIME_PERIOD = get_file_structure()
matt = _FILE_STRUCTURE.model_attributes
regions = sc.Regions(matt, )
time_periods = sc.TimePeriods(matt, )

### Making sure our input file has the correct format and correct columns
We use an example df with the complete fields and correct format to make sure our file is in the right shape

In [8]:
INPUT_FILE_PATH

PosixPath('/Users/fabianfuentes/git/ssp_mexico/ssp_modeling/input_data/sisepuede_raw_inputs_MEX_251209.csv')

In [9]:
##  BUILD BASE INPUTS
df_inputs_raw = pd.read_csv(INPUT_FILE_PATH)

# pull example data to fill in gaps
df_example_input = _EXAMPLES("input_data_frame")

In [10]:
# Double checking that our df is in the correct shape (Empty sets should be printed to make sure everything is Ok!)
g_utils.compare_dfs(df_example_input, df_inputs_raw)

Columns in df_example but not in df_input: set()
Columns in df_input but not in df_example: {'year', 'iso_alpha_3'}

In [11]:
# Ensure if time_period field exist
if 'time_period' not in df_inputs_raw.columns:
    logger.info("Adding 'time_period' column to df_inputs_raw")
    df_inputs_raw = df_inputs_raw.rename(columns={'period':'time_period'})
else:
    logger.info("'time_period' column already exists in df_inputs_raw")

2026-01-17 14:32:00,095 - INFO - 'time_period' column already exists in df_inputs_raw

In [12]:
# Fixes differences and makes sure that our df is in the correct format.
# Note: Edit this if you need more changes in your df

df_inputs_raw_complete = g_utils.add_missing_cols(df_example_input, df_inputs_raw.copy())
df_inputs_raw_complete.head()

No missing columns to add.

,year,ef_ippu_tonne_nf3_per_tonne_production_chemicals,ef_ippu_tonne_nf3_per_tonne_production_electronics,ef_ippu_tonne_sf6_per_mmm_gdp_other_product_manufacturing,ef_ippu_tonne_sf6_per_tonne_production_chemicals,ef_ippu_tonne_sf6_per_tonne_production_electronics,ef_ippu_tonne_sf6_per_tonne_production_metals,frac_agrc_bevs_and_spices_cl2_dry,frac_agrc_cereals_cl2_dry,frac_agrc_fibers_cl2_dry,...,nemomod_entc_scalar_availability_factor_pp_geothermal,nemomod_entc_scalar_availability_factor_pp_hydropower,nemomod_entc_scalar_availability_factor_pp_nuclear,nemomod_entc_scalar_availability_factor_pp_ocean,nemomod_entc_scalar_availability_factor_pp_oil,nemomod_entc_scalar_availability_factor_pp_solar,nemomod_entc_scalar_availability_factor_pp_waste_incineration,nemomod_entc_scalar_availability_factor_pp_wind,iso_alpha_3,region
0,2015,0.0,0.0,0.000264,0.0,3.663322e-08,1.403871e-07,0.729069,0.729069,0.729069,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,MEX,mexico
1,2016,0.0,0.0,0.000265,0.0,3.982696e-08,1.572880e-07,0.729069,0.729069,0.729069,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,MEX,mexico
2,2017,0.0,0.0,0.000266,0.0,3.638876e-08,1.617559e-07,0.729069,0.729069,0.729069,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,MEX,mexico
3,2018,0.0,0.0,0.000265,0.0,3.606106e-08,1.608518e-07,0.729069,0.729069,0.729069,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,MEX,mexico
4,2019,0.0,0.0,0.000265,0.0,3.455479e-08,1.636647e-07,0.729069,0.729069,0.729069,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,MEX,mexico

In [13]:
# Double checking that our df is in the correct shape (Empty sets should be printed to make sure everything is Ok!)
g_utils.compare_dfs(df_example_input, df_inputs_raw_complete)

Columns in df_example but not in df_input: set()
Columns in df_input but not in df_example: {'year', 'iso_alpha_3'}

In [14]:
# check region field
df_inputs_raw_complete['region'].unique()

array(['mexico'], dtype=object)

In [15]:
# Set region to country name
df_inputs_raw_complete['region'] = country_name
df_inputs_raw_complete['region'].head()

0    mexico
1    mexico
2    mexico
3    mexico
4    mexico
Name: region, dtype: object

In [16]:
crop_yield_factor = matt.get_variable("Crop Yield Factor")
crop_yield_factor.get_from_dataframe(df_inputs_raw_complete).iloc[0]

yf_agrc_bevs_and_spices_tonne_ha                     0.303484
yf_agrc_cereals_tonne_ha                             2.606545
yf_agrc_fibers_tonne_ha                              2.717737
yf_agrc_fruits_tonne_ha                             13.388626
yf_agrc_herbs_and_other_perennial_crops_tonne_ha     5.565740
yf_agrc_nuts_tonne_ha                                1.696694
yf_agrc_other_annual_tonne_ha                        0.812563
yf_agrc_other_woody_perennial_tonne_ha               9.341061
yf_agrc_pulses_tonne_ha                              0.877022
yf_agrc_rice_tonne_ha                                5.807900
yf_agrc_sugar_cane_tonne_ha                         62.069805
yf_agrc_tubers_tonne_ha                             26.565546
yf_agrc_vegetables_and_vines_tonne_ha               20.529640
Name: 0, dtype: float64

In [17]:
df_inputs_raw_complete['yf_agrc_cereals_tonne_ha'] *= 0.74

In [18]:
df_inputs_raw_complete['yf_agrc_sugar_cane_tonne_ha'] *= 0.85

In [19]:
initial_cropland_area_proportion = matt.get_variable("Initial Cropland Area Proportion")
initial_cropland_area_proportion.get_from_dataframe(df_inputs_raw_complete).iloc[0]

frac_agrc_initial_area_cropland_bevs_and_spices                    0.039683
frac_agrc_initial_area_cropland_cereals                            0.547623
frac_agrc_initial_area_cropland_fibers                             0.016593
frac_agrc_initial_area_cropland_fruits                             0.080738
frac_agrc_initial_area_cropland_herbs_and_other_perennial_crops    0.000805
frac_agrc_initial_area_cropland_nuts                               0.011489
frac_agrc_initial_area_cropland_other_annual                       0.120406
frac_agrc_initial_area_cropland_other_woody_perennial              0.004285
frac_agrc_initial_area_cropland_pulses                             0.093895
frac_agrc_initial_area_cropland_rice                               0.002219
frac_agrc_initial_area_cropland_sugar_cane                         0.041427
frac_agrc_initial_area_cropland_tubers                             0.004159
frac_agrc_initial_area_cropland_vegetables_and_vines               0.036678
Name: 0, dtype: float64

In [20]:
crop_demand_income_elasticity = matt.get_variable("Crop Demand Income Elasticity")
crop_demand_income_elasticity.get_from_dataframe(df_inputs_raw_complete).iloc[0]

elasticity_agrc_bevs_and_spices_demand_to_income                    0.291725
elasticity_agrc_cereals_demand_to_income                            0.194484
elasticity_agrc_fibers_demand_to_income                             0.194484
elasticity_agrc_fruits_demand_to_income                             0.243104
elasticity_agrc_herbs_and_other_perennial_crops_demand_to_income    0.194484
elasticity_agrc_nuts_demand_to_income                               0.243104
elasticity_agrc_other_annual_demand_to_income                       0.194484
elasticity_agrc_other_woody_perennial_demand_to_income              0.194484
elasticity_agrc_pulses_demand_to_income                             0.194484
elasticity_agrc_rice_demand_to_income                               0.097242
elasticity_agrc_sugar_cane_demand_to_income                         0.048621
elasticity_agrc_tubers_demand_to_income                             0.243104
elasticity_agrc_vegetables_and_vines_demand_to_income               0.243104
Name: 0, dtype: float64

In [21]:
initial_cropland_area_proportion = matt.get_variable("Initial Land Use Area Proportion")
initial_cropland_area_proportion.get_from_dataframe(df_inputs_raw_complete).iloc[0]

frac_lndu_initial_croplands            0.117388
frac_lndu_initial_flooded              0.007203
frac_lndu_initial_forests_mangroves    0.002717
frac_lndu_initial_forests_primary      0.107212
frac_lndu_initial_forests_secondary    0.278276
frac_lndu_initial_grasslands           0.104555
frac_lndu_initial_other                0.021969
frac_lndu_initial_pastures             0.064163
frac_lndu_initial_settlements          0.012671
frac_lndu_initial_shrublands           0.282650
frac_lndu_initial_wetlands             0.001197
Name: 0, dtype: float64

In [22]:
# List of land use fraction columns in the SISEPUEDE input
landuse_cols = [
    "frac_lndu_initial_croplands",
    "frac_lndu_initial_flooded",
    "frac_lndu_initial_forests_mangroves",
    "frac_lndu_initial_forests_primary",
    "frac_lndu_initial_forests_secondary",
    "frac_lndu_initial_grasslands",
    "frac_lndu_initial_other",
    "frac_lndu_initial_pastures",
    "frac_lndu_initial_settlements",
    "frac_lndu_initial_shrublands",
    "frac_lndu_initial_wetlands"
]

df_inputs_raw_complete.loc[:, "frac_lndu_initial_forests_primary"] = 0.11   # ~11%
df_inputs_raw_complete.loc[:, "frac_lndu_initial_settlements"]    = 0.013  # ~1.3%
df_inputs_raw_complete.loc[:, "frac_lndu_initial_shrublands"]     = 0.29   # ~29%


# Compute the row-wise sum of all land use fractions
row_sum = df_inputs_raw_complete[landuse_cols].sum(axis=1)

# Avoid division by zero just in case (should not happen, but safe)
row_sum = row_sum.replace(0, pd.NA)

# Divide each land use column by the row-wise sum
df_inputs_raw_complete[landuse_cols] = (
    df_inputs_raw_complete[landuse_cols].div(row_sum, axis=0)
)

In [23]:
initial_cropland_area_proportion.get_from_dataframe(df_inputs_raw_complete).iloc[0]

frac_lndu_initial_croplands            0.116172
frac_lndu_initial_flooded              0.007128
frac_lndu_initial_forests_mangroves    0.002689
frac_lndu_initial_forests_primary      0.108861
frac_lndu_initial_forests_secondary    0.275394
frac_lndu_initial_grasslands           0.103471
frac_lndu_initial_other                0.021741
frac_lndu_initial_pastures             0.063499
frac_lndu_initial_settlements          0.012865
frac_lndu_initial_shrublands           0.286996
frac_lndu_initial_wetlands             0.001184
Name: 0, dtype: float64

In [24]:
import pandas as pd

# Lista de prefijos de productos industriales
product_prefixes = [
    "frac_inen_energy_agriculture_and_livestock_",
    "frac_inen_energy_cement_",
    "frac_inen_energy_chemicals_",
    "frac_inen_energy_electronics_",
    "frac_inen_energy_glass_",
    "frac_inen_energy_lime_and_carbonite_",
    "frac_inen_energy_metals_",
    "frac_inen_energy_mining_",
    "frac_inen_energy_other_product_manufacturing_",
    "frac_inen_energy_paper_",
    "frac_inen_energy_plastic_",
    "frac_inen_energy_recycled_glass_",
    "frac_inen_energy_recycled_metals_",
    "frac_inen_energy_recycled_paper_",
    "frac_inen_energy_recycled_plastic_",
    "frac_inen_energy_recycled_rubber_and_leather_",
    "frac_inen_energy_recycled_textiles_",
    "frac_inen_energy_recycled_wood_",
    "frac_inen_energy_rubber_and_leather_",
    "frac_inen_energy_textiles_",
    "frac_inen_energy_wood_"
]

# Targets para TODOS los productos
targets = {
    "electricity": 0.48,
    "natural_gas": 0.27,
    "oil": 0.17
}

# Iterar sobre cada prefijo / producto
for prefix in product_prefixes:

    # Identificar las columnas de ese producto
    cols = [c for c in df_inputs_raw_complete.columns if c.startswith(prefix)]
    if len(cols) == 0:
        continue  # si no hay columnas, pasar al siguiente producto

    # Columnas específicas que deben fijarse
    target_cols = {
        prefix + "electricity": targets["electricity"],
        prefix + "natural_gas": targets["natural_gas"],
        prefix + "oil": targets["oil"]
    }

    # Aplicar valores fijos a TODAS las filas
    for col, val in target_cols.items():
        if col in df_inputs_raw_complete.columns:
            df_inputs_raw_complete.loc[:, col] = val

    # Reescalar el resto para que sumen 1
    for i in df_inputs_raw_complete.index:

        row = df_inputs_raw_complete.loc[i, cols]

        fixed_sum = sum(val for key, val in target_cols.items() if key in row.index)

        remaining = 1 - fixed_sum

        other_cols = [c for c in cols if c not in target_cols]
        orig_sum_other = row[other_cols].sum()

        if orig_sum_other > 0:
            df_inputs_raw_complete.loc[i, other_cols] = (
                row[other_cols] / orig_sum_other * remaining
            )
        else:
            df_inputs_raw_complete.loc[i, other_cols] = 0

In [25]:
industrial_energy_fraction_coal = matt.get_variable("Industrial Energy Fuel Fraction Coal")
industrial_energy_fraction_coal.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_coal      0.000000
frac_inen_energy_cement_coal                         0.016987
frac_inen_energy_chemicals_coal                      0.000000
frac_inen_energy_electronics_coal                    0.000000
frac_inen_energy_glass_coal                          0.016987
frac_inen_energy_lime_and_carbonite_coal             0.016987
frac_inen_energy_metals_coal                         0.070561
frac_inen_energy_mining_coal                         0.002189
frac_inen_energy_other_product_manufacturing_coal    0.009927
frac_inen_energy_paper_coal                          0.000000
frac_inen_energy_plastic_coal                        0.000000
frac_inen_energy_recycled_glass_coal                 0.016987
frac_inen_energy_recycled_metals_coal                0.070561
frac_inen_energy_recycled_paper_coal                 0.000000
frac_inen_energy_recycled_plastic_coal               0.000000
frac_inen_energy_recycled_rubber_and_leather_coal    0.000000
frac_inen_energy_recycled_textiles_coal              0.000000
frac_inen_energy_recycled_wood_coal                  0.000000
frac_inen_energy_rubber_and_leather_coal             0.000000
frac_inen_energy_textiles_coal                       0.000000
frac_inen_energy_wood_coal                           0.000000
Name: 7, dtype: float64

In [26]:
industrial_energy_fraction_coke = matt.get_variable("Industrial Energy Fuel Fraction Coke")
industrial_energy_fraction_coke.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_coke      0.000000
frac_inen_energy_cement_coke                         0.001887
frac_inen_energy_chemicals_coke                      0.000000
frac_inen_energy_electronics_coke                    0.000000
frac_inen_energy_glass_coke                          0.001887
frac_inen_energy_lime_and_carbonite_coke             0.001887
frac_inen_energy_metals_coke                         0.007840
frac_inen_energy_mining_coke                         0.000243
frac_inen_energy_other_product_manufacturing_coke    0.001103
frac_inen_energy_paper_coke                          0.000000
frac_inen_energy_plastic_coke                        0.000000
frac_inen_energy_recycled_glass_coke                 0.001887
frac_inen_energy_recycled_metals_coke                0.007840
frac_inen_energy_recycled_paper_coke                 0.000000
frac_inen_energy_recycled_plastic_coke               0.000000
frac_inen_energy_recycled_rubber_and_leather_coke    0.000000
frac_inen_energy_recycled_textiles_coke              0.000000
frac_inen_energy_recycled_wood_coke                  0.000000
frac_inen_energy_rubber_and_leather_coke             0.000000
frac_inen_energy_textiles_coke                       0.000000
frac_inen_energy_wood_coke                           0.000000
Name: 7, dtype: float64

In [27]:
industrial_energy_fraction_diesel = matt.get_variable("Industrial Energy Fuel Fraction Diesel")
industrial_energy_fraction_diesel.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_diesel      0.040000
frac_inen_energy_cement_diesel                         0.030563
frac_inen_energy_chemicals_diesel                      0.040000
frac_inen_energy_electronics_diesel                    0.040000
frac_inen_energy_glass_diesel                          0.030563
frac_inen_energy_lime_and_carbonite_diesel             0.030563
frac_inen_energy_metals_diesel                         0.000800
frac_inen_energy_mining_diesel                         0.034875
frac_inen_energy_other_product_manufacturing_diesel    0.014245
frac_inen_energy_paper_diesel                          0.040000
frac_inen_energy_plastic_diesel                        0.040000
frac_inen_energy_recycled_glass_diesel                 0.030563
frac_inen_energy_recycled_metals_diesel                0.000800
frac_inen_energy_recycled_paper_diesel                 0.040000
frac_inen_energy_recycled_plastic_diesel               0.040000
frac_inen_energy_recycled_rubber_and_leather_diesel    0.040000
frac_inen_energy_recycled_textiles_diesel              0.000000
frac_inen_energy_recycled_wood_diesel                  0.000000
frac_inen_energy_rubber_and_leather_diesel             0.040000
frac_inen_energy_textiles_diesel                       0.000000
frac_inen_energy_wood_diesel                           0.000000
Name: 7, dtype: float64

In [28]:
industrial_energy_fraction_electricity = matt.get_variable("Industrial Energy Fuel Fraction Electricity")
industrial_energy_fraction_electricity.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_electricity      0.48
frac_inen_energy_cement_electricity                         0.48
frac_inen_energy_chemicals_electricity                      0.48
frac_inen_energy_electronics_electricity                    0.48
frac_inen_energy_glass_electricity                          0.48
frac_inen_energy_lime_and_carbonite_electricity             0.48
frac_inen_energy_metals_electricity                         0.48
frac_inen_energy_mining_electricity                         0.48
frac_inen_energy_other_product_manufacturing_electricity    0.48
frac_inen_energy_paper_electricity                          0.48
frac_inen_energy_plastic_electricity                        0.48
frac_inen_energy_recycled_glass_electricity                 0.48
frac_inen_energy_recycled_metals_electricity                0.48
frac_inen_energy_recycled_paper_electricity                 0.48
frac_inen_energy_recycled_plastic_electricity               0.48
frac_inen_energy_recycled_rubber_and_leather_electricity    0.48
frac_inen_energy_recycled_textiles_electricity              0.48
frac_inen_energy_recycled_wood_electricity                  0.48
frac_inen_energy_rubber_and_leather_electricity             0.48
frac_inen_energy_textiles_electricity                       0.48
frac_inen_energy_wood_electricity                           0.48
Name: 7, dtype: float64

In [29]:
industrial_energy_fraction_electricity.get_from_dataframe(df_inputs_raw_complete).head(35)

,frac_inen_energy_agriculture_and_livestock_electricity,frac_inen_energy_cement_electricity,frac_inen_energy_chemicals_electricity,frac_inen_energy_electronics_electricity,frac_inen_energy_glass_electricity,frac_inen_energy_lime_and_carbonite_electricity,frac_inen_energy_metals_electricity,frac_inen_energy_mining_electricity,frac_inen_energy_other_product_manufacturing_electricity,frac_inen_energy_paper_electricity,...,frac_inen_energy_recycled_glass_electricity,frac_inen_energy_recycled_metals_electricity,frac_inen_energy_recycled_paper_electricity,frac_inen_energy_recycled_plastic_electricity,frac_inen_energy_recycled_rubber_and_leather_electricity,frac_inen_energy_recycled_textiles_electricity,frac_inen_energy_recycled_wood_electricity,frac_inen_energy_rubber_and_leather_electricity,frac_inen_energy_textiles_electricity,frac_inen_energy_wood_electricity
0,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
1,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
2,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
3,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
4,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
5,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
6,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
7,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
8,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
9,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
10,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
11,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
12,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
13,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
14,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
15,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
16,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
17,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
18,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
19,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
20,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
21,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
22,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
23,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
24,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
25,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
26,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
27,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
28,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
29,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
30,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
31,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
32,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
33,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48
34,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,...,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48,0.48

In [30]:
industrial_energy_fraction_electricity.get_from_dataframe(df_inputs_raw_complete).iloc[7].mean()

np.float64(0.4800000000000001)

In [31]:
industrial_energy_fraction_furnace_gas = matt.get_variable("Industrial Energy Fuel Fraction Furnace Gas")
industrial_energy_fraction_furnace_gas.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_furnace_gas      0.0
frac_inen_energy_cement_furnace_gas                         0.0
frac_inen_energy_chemicals_furnace_gas                      0.0
frac_inen_energy_electronics_furnace_gas                    0.0
frac_inen_energy_glass_furnace_gas                          0.0
frac_inen_energy_lime_and_carbonite_furnace_gas             0.0
frac_inen_energy_metals_furnace_gas                         0.0
frac_inen_energy_mining_furnace_gas                         0.0
frac_inen_energy_other_product_manufacturing_furnace_gas    0.0
frac_inen_energy_paper_furnace_gas                          0.0
frac_inen_energy_plastic_furnace_gas                        0.0
frac_inen_energy_recycled_glass_furnace_gas                 0.0
frac_inen_energy_recycled_metals_furnace_gas                0.0
frac_inen_energy_recycled_paper_furnace_gas                 0.0
frac_inen_energy_recycled_plastic_furnace_gas               0.0
frac_inen_energy_recycled_rubber_and_leather_furnace_gas    0.0
frac_inen_energy_recycled_textiles_furnace_gas              0.0
frac_inen_energy_recycled_wood_furnace_gas                  0.0
frac_inen_energy_rubber_and_leather_furnace_gas             0.0
frac_inen_energy_textiles_furnace_gas                       0.0
frac_inen_energy_wood_furnace_gas                           0.0
Name: 7, dtype: float64

In [32]:
industrial_energy_fraction_furnace_gasoline = matt.get_variable("Industrial Energy Fuel Fraction Gasoline")
industrial_energy_fraction_furnace_gasoline.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_gasoline      0.040000
frac_inen_energy_cement_gasoline                         0.030563
frac_inen_energy_chemicals_gasoline                      0.040000
frac_inen_energy_electronics_gasoline                    0.040000
frac_inen_energy_glass_gasoline                          0.030563
frac_inen_energy_lime_and_carbonite_gasoline             0.030563
frac_inen_energy_metals_gasoline                         0.000800
frac_inen_energy_mining_gasoline                         0.034875
frac_inen_energy_other_product_manufacturing_gasoline    0.014245
frac_inen_energy_paper_gasoline                          0.040000
frac_inen_energy_plastic_gasoline                        0.040000
frac_inen_energy_recycled_glass_gasoline                 0.030563
frac_inen_energy_recycled_metals_gasoline                0.000800
frac_inen_energy_recycled_paper_gasoline                 0.040000
frac_inen_energy_recycled_plastic_gasoline               0.040000
frac_inen_energy_recycled_rubber_and_leather_gasoline    0.040000
frac_inen_energy_recycled_textiles_gasoline              0.000000
frac_inen_energy_recycled_wood_gasoline                  0.000000
frac_inen_energy_rubber_and_leather_gasoline             0.040000
frac_inen_energy_textiles_gasoline                       0.000000
frac_inen_energy_wood_gasoline                           0.000000
Name: 7, dtype: float64

In [33]:
industrial_energy_fraction_geothermal = matt.get_variable("Industrial Energy Fuel Fraction Geothermal")
industrial_energy_fraction_geothermal.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_mining_geothermal    0.0
Name: 7, dtype: float64

In [34]:
industrial_energy_fraction_hydrocarbon_gas_liquids = matt.get_variable("Industrial Energy Fuel Fraction Hydrocarbon Gas Liquids")
industrial_energy_fraction_hydrocarbon_gas_liquids.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_hydrocarbon_gas_liquids      0.0
frac_inen_energy_cement_hydrocarbon_gas_liquids                         0.0
frac_inen_energy_chemicals_hydrocarbon_gas_liquids                      0.0
frac_inen_energy_electronics_hydrocarbon_gas_liquids                    0.0
frac_inen_energy_glass_hydrocarbon_gas_liquids                          0.0
frac_inen_energy_lime_and_carbonite_hydrocarbon_gas_liquids             0.0
frac_inen_energy_metals_hydrocarbon_gas_liquids                         0.0
frac_inen_energy_mining_hydrocarbon_gas_liquids                         0.0
frac_inen_energy_other_product_manufacturing_hydrocarbon_gas_liquids    0.0
frac_inen_energy_paper_hydrocarbon_gas_liquids                          0.0
frac_inen_energy_plastic_hydrocarbon_gas_liquids                        0.0
frac_inen_energy_recycled_glass_hydrocarbon_gas_liquids                 0.0
frac_inen_energy_recycled_metals_hydrocarbon_gas_liquids                0.0
frac_inen_energy_recycled_paper_hydrocarbon_gas_liquids                 0.0
frac_inen_energy_recycled_plastic_hydrocarbon_gas_liquids               0.0
frac_inen_energy_recycled_rubber_and_leather_hydrocarbon_gas_liquids    0.0
frac_inen_energy_recycled_textiles_hydrocarbon_gas_liquids              0.0
frac_inen_energy_recycled_wood_hydrocarbon_gas_liquids                  0.0
frac_inen_energy_rubber_and_leather_hydrocarbon_gas_liquids             0.0
frac_inen_energy_textiles_hydrocarbon_gas_liquids                       0.0
frac_inen_energy_wood_hydrocarbon_gas_liquids                           0.0
Name: 7, dtype: float64

In [35]:
industrial_energy_fraction_hydrogen = matt.get_variable("Industrial Energy Fuel Fraction Hydrogen")
industrial_energy_fraction_hydrogen.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_hydrogen      0.0
frac_inen_energy_cement_hydrogen                         0.0
frac_inen_energy_chemicals_hydrogen                      0.0
frac_inen_energy_electronics_hydrogen                    0.0
frac_inen_energy_glass_hydrogen                          0.0
frac_inen_energy_lime_and_carbonite_hydrogen             0.0
frac_inen_energy_metals_hydrogen                         0.0
frac_inen_energy_mining_hydrogen                         0.0
frac_inen_energy_other_product_manufacturing_hydrogen    0.0
frac_inen_energy_paper_hydrogen                          0.0
frac_inen_energy_plastic_hydrogen                        0.0
frac_inen_energy_recycled_glass_hydrogen                 0.0
frac_inen_energy_recycled_metals_hydrogen                0.0
frac_inen_energy_recycled_paper_hydrogen                 0.0
frac_inen_energy_recycled_plastic_hydrogen               0.0
frac_inen_energy_recycled_rubber_and_leather_hydrogen    0.0
frac_inen_energy_recycled_textiles_hydrogen              0.0
frac_inen_energy_recycled_wood_hydrogen                  0.0
frac_inen_energy_rubber_and_leather_hydrogen             0.0
frac_inen_energy_textiles_hydrogen                       0.0
frac_inen_energy_wood_hydrogen                           0.0
Name: 7, dtype: float64

In [36]:
industrial_energy_fraction_kerosene = matt.get_variable("Industrial Energy Fuel Fraction Kerosene")
industrial_energy_fraction_kerosene.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_kerosene      0.0
frac_inen_energy_cement_kerosene                         0.0
frac_inen_energy_chemicals_kerosene                      0.0
frac_inen_energy_electronics_kerosene                    0.0
frac_inen_energy_glass_kerosene                          0.0
frac_inen_energy_lime_and_carbonite_kerosene             0.0
frac_inen_energy_metals_kerosene                         0.0
frac_inen_energy_mining_kerosene                         0.0
frac_inen_energy_other_product_manufacturing_kerosene    0.0
frac_inen_energy_paper_kerosene                          0.0
frac_inen_energy_plastic_kerosene                        0.0
frac_inen_energy_recycled_glass_kerosene                 0.0
frac_inen_energy_recycled_metals_kerosene                0.0
frac_inen_energy_recycled_paper_kerosene                 0.0
frac_inen_energy_recycled_plastic_kerosene               0.0
frac_inen_energy_recycled_rubber_and_leather_kerosene    0.0
frac_inen_energy_recycled_textiles_kerosene              0.0
frac_inen_energy_recycled_wood_kerosene                  0.0
frac_inen_energy_rubber_and_leather_kerosene             0.0
frac_inen_energy_textiles_kerosene                       0.0
frac_inen_energy_wood_kerosene                           0.0
Name: 7, dtype: float64

In [37]:
industrial_energy_fraction_natural_gas = matt.get_variable("Industrial Energy Fuel Fraction Natural Gas")
industrial_energy_fraction_natural_gas.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_natural_gas      0.27
frac_inen_energy_cement_natural_gas                         0.27
frac_inen_energy_chemicals_natural_gas                      0.27
frac_inen_energy_electronics_natural_gas                    0.27
frac_inen_energy_glass_natural_gas                          0.27
frac_inen_energy_lime_and_carbonite_natural_gas             0.27
frac_inen_energy_metals_natural_gas                         0.27
frac_inen_energy_mining_natural_gas                         0.27
frac_inen_energy_other_product_manufacturing_natural_gas    0.27
frac_inen_energy_paper_natural_gas                          0.27
frac_inen_energy_plastic_natural_gas                        0.27
frac_inen_energy_recycled_glass_natural_gas                 0.27
frac_inen_energy_recycled_metals_natural_gas                0.27
frac_inen_energy_recycled_paper_natural_gas                 0.27
frac_inen_energy_recycled_plastic_natural_gas               0.27
frac_inen_energy_recycled_rubber_and_leather_natural_gas    0.27
frac_inen_energy_recycled_textiles_natural_gas              0.27
frac_inen_energy_recycled_wood_natural_gas                  0.27
frac_inen_energy_rubber_and_leather_natural_gas             0.27
frac_inen_energy_textiles_natural_gas                       0.27
frac_inen_energy_wood_natural_gas                           0.27
Name: 7, dtype: float64

In [38]:
industrial_energy_fraction_natural_gas = matt.get_variable("Industrial Energy Fuel Fraction Natural Gas")
industrial_energy_fraction_natural_gas.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_natural_gas      0.27
frac_inen_energy_cement_natural_gas                         0.27
frac_inen_energy_chemicals_natural_gas                      0.27
frac_inen_energy_electronics_natural_gas                    0.27
frac_inen_energy_glass_natural_gas                          0.27
frac_inen_energy_lime_and_carbonite_natural_gas             0.27
frac_inen_energy_metals_natural_gas                         0.27
frac_inen_energy_mining_natural_gas                         0.27
frac_inen_energy_other_product_manufacturing_natural_gas    0.27
frac_inen_energy_paper_natural_gas                          0.27
frac_inen_energy_plastic_natural_gas                        0.27
frac_inen_energy_recycled_glass_natural_gas                 0.27
frac_inen_energy_recycled_metals_natural_gas                0.27
frac_inen_energy_recycled_paper_natural_gas                 0.27
frac_inen_energy_recycled_plastic_natural_gas               0.27
frac_inen_energy_recycled_rubber_and_leather_natural_gas    0.27
frac_inen_energy_recycled_textiles_natural_gas              0.27
frac_inen_energy_recycled_wood_natural_gas                  0.27
frac_inen_energy_rubber_and_leather_natural_gas             0.27
frac_inen_energy_textiles_natural_gas                       0.27
frac_inen_energy_wood_natural_gas                           0.27
Name: 7, dtype: float64

In [39]:
industrial_energy_fraction_natural_gas.get_from_dataframe(df_inputs_raw_complete).head(35)

,frac_inen_energy_agriculture_and_livestock_natural_gas,frac_inen_energy_cement_natural_gas,frac_inen_energy_chemicals_natural_gas,frac_inen_energy_electronics_natural_gas,frac_inen_energy_glass_natural_gas,frac_inen_energy_lime_and_carbonite_natural_gas,frac_inen_energy_metals_natural_gas,frac_inen_energy_mining_natural_gas,frac_inen_energy_other_product_manufacturing_natural_gas,frac_inen_energy_paper_natural_gas,...,frac_inen_energy_recycled_glass_natural_gas,frac_inen_energy_recycled_metals_natural_gas,frac_inen_energy_recycled_paper_natural_gas,frac_inen_energy_recycled_plastic_natural_gas,frac_inen_energy_recycled_rubber_and_leather_natural_gas,frac_inen_energy_recycled_textiles_natural_gas,frac_inen_energy_recycled_wood_natural_gas,frac_inen_energy_rubber_and_leather_natural_gas,frac_inen_energy_textiles_natural_gas,frac_inen_energy_wood_natural_gas
0,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
1,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
2,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
3,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
4,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
5,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
6,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
7,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
8,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
9,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
10,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
11,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
12,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
13,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
14,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
15,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
16,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
17,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
18,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
19,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
20,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
21,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
22,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
23,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
24,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
25,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
26,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
28,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
29,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
30,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
31,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
32,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
33,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27
34,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27,0.27

In [40]:
industrial_energy_fraction_natural_gas.get_from_dataframe(df_inputs_raw_complete).iloc[7].mean()

np.float64(0.2699999999999999)

In [41]:
industrial_energy_fraction_oil = matt.get_variable("Industrial Energy Fuel Fraction Oil")
industrial_energy_fraction_oil.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_oil      0.17
frac_inen_energy_cement_oil                         0.17
frac_inen_energy_chemicals_oil                      0.17
frac_inen_energy_electronics_oil                    0.17
frac_inen_energy_glass_oil                          0.17
frac_inen_energy_lime_and_carbonite_oil             0.17
frac_inen_energy_metals_oil                         0.17
frac_inen_energy_mining_oil                         0.17
frac_inen_energy_other_product_manufacturing_oil    0.17
frac_inen_energy_paper_oil                          0.17
frac_inen_energy_plastic_oil                        0.17
frac_inen_energy_recycled_glass_oil                 0.17
frac_inen_energy_recycled_metals_oil                0.17
frac_inen_energy_recycled_paper_oil                 0.17
frac_inen_energy_recycled_plastic_oil               0.17
frac_inen_energy_recycled_rubber_and_leather_oil    0.17
frac_inen_energy_recycled_textiles_oil              0.17
frac_inen_energy_recycled_wood_oil                  0.17
frac_inen_energy_rubber_and_leather_oil             0.17
frac_inen_energy_textiles_oil                       0.17
frac_inen_energy_wood_oil                           0.17
Name: 7, dtype: float64

In [42]:
industrial_energy_fraction_oil.get_from_dataframe(df_inputs_raw_complete).head(35)

,frac_inen_energy_agriculture_and_livestock_oil,frac_inen_energy_cement_oil,frac_inen_energy_chemicals_oil,frac_inen_energy_electronics_oil,frac_inen_energy_glass_oil,frac_inen_energy_lime_and_carbonite_oil,frac_inen_energy_metals_oil,frac_inen_energy_mining_oil,frac_inen_energy_other_product_manufacturing_oil,frac_inen_energy_paper_oil,...,frac_inen_energy_recycled_glass_oil,frac_inen_energy_recycled_metals_oil,frac_inen_energy_recycled_paper_oil,frac_inen_energy_recycled_plastic_oil,frac_inen_energy_recycled_rubber_and_leather_oil,frac_inen_energy_recycled_textiles_oil,frac_inen_energy_recycled_wood_oil,frac_inen_energy_rubber_and_leather_oil,frac_inen_energy_textiles_oil,frac_inen_energy_wood_oil
0,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
1,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
2,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
3,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
4,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
5,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
6,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
7,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
8,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
9,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
10,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
11,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
12,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
13,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
14,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
15,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
16,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
18,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
19,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
20,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
21,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
22,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
23,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
24,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
25,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
26,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
27,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
28,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
29,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
30,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
31,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
32,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
33,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17
34,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,...,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17,0.17

In [43]:
industrial_energy_fraction_biomass = matt.get_variable("Industrial Energy Fuel Fraction Solid Biomass")
industrial_energy_fraction_biomass.get_from_dataframe(df_inputs_raw_complete).iloc[7]

frac_inen_energy_agriculture_and_livestock_solid_biomass      0.000000
frac_inen_energy_cement_solid_biomass                         0.000000
frac_inen_energy_chemicals_solid_biomass                      0.000000
frac_inen_energy_electronics_solid_biomass                    0.000000
frac_inen_energy_glass_solid_biomass                          0.000000
frac_inen_energy_lime_and_carbonite_solid_biomass             0.000000
frac_inen_energy_metals_solid_biomass                         0.000000
frac_inen_energy_mining_solid_biomass                         0.007818
frac_inen_energy_other_product_manufacturing_solid_biomass    0.039224
frac_inen_energy_paper_solid_biomass                          0.000000
frac_inen_energy_plastic_solid_biomass                        0.000000
frac_inen_energy_recycled_glass_solid_biomass                 0.000000
frac_inen_energy_recycled_metals_solid_biomass                0.000000
frac_inen_energy_recycled_paper_solid_biomass                 0.000000
frac_inen_energy_recycled_plastic_solid_biomass               0.000000
frac_inen_energy_recycled_rubber_and_leather_solid_biomass    0.000000
frac_inen_energy_recycled_textiles_solid_biomass              0.000000
frac_inen_energy_recycled_wood_solid_biomass                  0.000000
frac_inen_energy_rubber_and_leather_solid_biomass             0.000000
frac_inen_energy_textiles_solid_biomass                       0.000000
frac_inen_energy_wood_solid_biomass                           0.000000
Name: 7, dtype: float64

In [44]:
cols = [c for c in df_inputs_raw_complete.columns if c.startswith("yf_agrc_")]
df_inputs_raw_complete[cols].head()

,yf_agrc_bevs_and_spices_tonne_ha,yf_agrc_cereals_tonne_ha,yf_agrc_fibers_tonne_ha,yf_agrc_fruits_tonne_ha,yf_agrc_herbs_and_other_perennial_crops_tonne_ha,yf_agrc_nuts_tonne_ha,yf_agrc_other_annual_tonne_ha,yf_agrc_other_woody_perennial_tonne_ha,yf_agrc_pulses_tonne_ha,yf_agrc_rice_tonne_ha,yf_agrc_sugar_cane_tonne_ha,yf_agrc_tubers_tonne_ha,yf_agrc_vegetables_and_vines_tonne_ha
0,0.303484,1.928843,2.717737,13.388626,5.565740,1.696694,0.812563,9.341061,0.877022,5.8079,52.759334,26.565546,20.529640
1,0.259844,2.081412,2.809741,13.737473,6.132020,1.756926,1.027836,9.361449,0.934484,6.1346,52.215075,27.559922,21.361121
2,0.269857,2.116396,3.031121,13.945799,9.709369,1.748638,0.985574,10.143155,0.976767,6.3900,53.302871,28.495376,23.175588
3,0.283318,2.135265,3.089746,13.810068,8.912849,1.778275,1.017304,10.775415,1.031504,6.2848,52.255679,29.327011,24.410027
4,0.294515,2.223772,2.796360,14.112108,6.907958,1.760671,0.972611,11.296426,1.045168,6.3662,53.856450,29.502182,23.821076

In [45]:
cols = [c for c in df_inputs_raw_complete.columns if c.startswith("prodinit_ippu_")]
df_inputs_raw_complete[cols].head()

,prodinit_ippu_cement_tonne,prodinit_ippu_chemicals_tonne,prodinit_ippu_electronics_tonne,prodinit_ippu_glass_tonne,prodinit_ippu_lime_and_carbonite_tonne,prodinit_ippu_metals_tonne,prodinit_ippu_mining_tonne,prodinit_ippu_paper_tonne,prodinit_ippu_plastic_tonne,prodinit_ippu_rubber_and_leather_tonne,prodinit_ippu_textiles_tonne,prodinit_ippu_recycled_glass_tonne,prodinit_ippu_recycled_metals_tonne,prodinit_ippu_recycled_paper_tonne,prodinit_ippu_recycled_plastic_tonne,prodinit_ippu_recycled_rubber_and_leather_tonne,prodinit_ippu_recycled_textiles_tonne,prodinit_ippu_wood_tonne
0,34994250.0,4.701024e+06,268117.585026,1.091477e+06,37016.072606,2.699677e+07,2.268598e+08,6.812709e+06,6.760267e+06,265549.073632,1.189314e+06,0.0,0.0,0.0,0.0,0.0,0.0,18333230.0
1,36028600.0,4.189485e+06,248575.329929,1.025014e+06,51714.320922,2.562179e+07,1.906182e+08,6.182053e+06,6.368468e+06,236850.494100,1.105013e+06,0.0,0.0,0.0,0.0,0.0,0.0,18333230.0
2,36511800.0,4.582370e+06,274810.170516,1.009615e+06,41151.135798,2.639780e+07,1.589087e+08,6.647999e+06,6.316863e+06,234688.777427,1.031593e+06,0.0,0.0,0.0,0.0,0.0,0.0,18333230.0
3,36489150.0,4.447272e+06,278291.884002,1.035601e+06,44005.620070,2.797606e+07,1.685579e+08,6.435588e+06,6.503246e+06,245879.638766,1.020578e+06,0.0,0.0,0.0,0.0,0.0,0.0,18333230.0
4,34095800.0,4.556463e+06,292482.324266,1.056164e+06,7785.492329,2.893788e+07,1.643216e+08,6.531812e+06,6.558685e+06,261075.178107,1.005969e+06,0.0,0.0,0.0,0.0,0.0,0.0,18333230.0

USGS – Mineral Commodity Summary (Cement, 2021) → México ≈ 35 Mt

In [46]:
df_inputs_raw_complete['prodinit_ippu_cement_tonne'] *= 0.755

More rasonable

In [47]:
df_inputs_raw_complete['prodinit_ippu_electronics_tonne'] *= 0.02

Low production of glass

In [48]:
df_inputs_raw_complete['prodinit_ippu_glass_tonne'] *= 2

lime and carbonite

In [49]:
df_inputs_raw_complete['prodinit_ippu_lime_and_carbonite_tonne'] *= 2

🎯 Producción minera total estimada para México 2020

Sumando solo los grandes rubros:
	•	Caliza: ~180 Mt

	•	Arena + grava: ~130 Mt

	•	Yeso + otros no metálicos: ~15 Mt

	•	Minerales metálicos varios: ~20 Mt

In [50]:
df_inputs_raw_complete['prodinit_ippu_mining_tonne'] *= 1.1

In [51]:
df_inputs_raw_complete['consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_elec_appliances'] *= 0.3

df_inputs_raw_complete['consumpinit_scoe_tj_per_mmmgdp_commercial_municipal_heat_energy'] *= 0.3

df_inputs_raw_complete['consumpinit_scoe_gj_per_hh_residential_heat_energy'] *= 0.3

df_inputs_raw_complete['consumpinit_scoe_gj_per_hh_residential_elec_appliances'] *= 0.3

In [52]:
cols = [c for c in df_inputs_raw_complete.columns if c.startswith("prodinit_ippu_")]
df_inputs_raw_complete[cols].iloc[0]

prodinit_ippu_cement_tonne                         2.642066e+07
prodinit_ippu_chemicals_tonne                      4.701024e+06
prodinit_ippu_electronics_tonne                    5.362352e+03
prodinit_ippu_glass_tonne                          2.182955e+06
prodinit_ippu_lime_and_carbonite_tonne             7.403215e+04
prodinit_ippu_metals_tonne                         2.699677e+07
prodinit_ippu_mining_tonne                         2.495458e+08
prodinit_ippu_paper_tonne                          6.812709e+06
prodinit_ippu_plastic_tonne                        6.760267e+06
prodinit_ippu_rubber_and_leather_tonne             2.655491e+05
prodinit_ippu_textiles_tonne                       1.189314e+06
prodinit_ippu_recycled_glass_tonne                 0.000000e+00
prodinit_ippu_recycled_metals_tonne                0.000000e+00
prodinit_ippu_recycled_paper_tonne                 0.000000e+00
prodinit_ippu_recycled_plastic_tonne               0.000000e+00
prodinit_ippu_recycled_rubber_and_leather_tonne    0.000000e+00
prodinit_ippu_recycled_textiles_tonne              0.000000e+00
prodinit_ippu_wood_tonne                           1.833323e+07
Name: 0, dtype: float64

In [53]:
df_inputs_raw_complete['elasticity_ippu_rubber_and_leather_production_to_gdp']

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    1.0
28    1.0
29    1.0
30    1.0
31    1.0
32    1.0
33    1.0
34    1.0
35    1.0
36    1.0
37    1.0
38    1.0
39    1.0
40    1.0
41    1.0
42    1.0
43    1.0
44    1.0
45    1.0
46    1.0
47    1.0
48    1.0
49    1.0
50    1.0
51    1.0
52    1.0
53    1.0
54    1.0
55    1.0
Name: elasticity_ippu_rubber_and_leather_production_to_gdp, dtype: float64

In [54]:
df_inputs_raw_complete['elasticity_ippu_metals_production_to_gdp']

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    1.0
28    1.0
29    1.0
30    1.0
31    1.0
32    1.0
33    1.0
34    1.0
35    1.0
36    1.0
37    1.0
38    1.0
39    1.0
40    1.0
41    1.0
42    1.0
43    1.0
44    1.0
45    1.0
46    1.0
47    1.0
48    1.0
49    1.0
50    1.0
51    1.0
52    1.0
53    1.0
54    1.0
55    1.0
Name: elasticity_ippu_metals_production_to_gdp, dtype: float64

In [55]:
df_inputs_raw_complete['elasticity_ippu_metals_production_to_gdp'] = 1.0

In [56]:
df_inputs_raw_complete['elasticity_ippu_rubber_and_leather_production_to_gdp'] = 1.0
df_inputs_raw_complete['elasticity_ippu_rubber_and_leather_production_to_gdp']

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    1.0
28    1.0
29    1.0
30    1.0
31    1.0
32    1.0
33    1.0
34    1.0
35    1.0
36    1.0
37    1.0
38    1.0
39    1.0
40    1.0
41    1.0
42    1.0
43    1.0
44    1.0
45    1.0
46    1.0
47    1.0
48    1.0
49    1.0
50    1.0
51    1.0
52    1.0
53    1.0
54    1.0
55    1.0
Name: elasticity_ippu_rubber_and_leather_production_to_gdp, dtype: float64

In [57]:
df_inputs_raw_complete['elasticity_ippu_cement_production_to_gdp']

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    1.0
28    1.0
29    1.0
30    1.0
31    1.0
32    1.0
33    1.0
34    1.0
35    1.0
36    1.0
37    1.0
38    1.0
39    1.0
40    1.0
41    1.0
42    1.0
43    1.0
44    1.0
45    1.0
46    1.0
47    1.0
48    1.0
49    1.0
50    1.0
51    1.0
52    1.0
53    1.0
54    1.0
55    1.0
Name: elasticity_ippu_cement_production_to_gdp, dtype: float64

In [58]:
df_inputs_raw_complete['elasticity_ippu_cement_production_to_gdp'] = 1.0
df_inputs_raw_complete['elasticity_ippu_cement_production_to_gdp']

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    1.0
28    1.0
29    1.0
30    1.0
31    1.0
32    1.0
33    1.0
34    1.0
35    1.0
36    1.0
37    1.0
38    1.0
39    1.0
40    1.0
41    1.0
42    1.0
43    1.0
44    1.0
45    1.0
46    1.0
47    1.0
48    1.0
49    1.0
50    1.0
51    1.0
52    1.0
53    1.0
54    1.0
55    1.0
Name: elasticity_ippu_cement_production_to_gdp, dtype: float64

In [59]:
DATA_DIR_PATH

PosixPath('/Users/fabianfuentes/git/ssp_mexico/ssp_modeling/input_data')

In [60]:
df_inputs_raw_complete.to_csv(DATA_DIR_PATH.joinpath("sisepuede_raw_inputs_MEX_251209.csv"), index=False)

## Let's Modify the  LNDU Reallocation factor

In [ ]:
if set_lndu_reallocation_factor_to_zero_flag:
    df_inputs_raw_complete['lndu_reallocation_factor'] = 0

df_inputs_raw_complete['lndu_reallocation_factor'].mean()

In [ ]:
df_inputs_raw_complete = df_inputs_raw_complete[df_inputs_raw_complete['time_period'].between(0, 35)]
df_inputs_raw_complete['time_period'].unique()

#  Let's try building transformations using this

In [ ]:
transformers = trf.transformers.Transformers(
    {},
    attr_time_period = _ATTRIBUTE_TABLE_TIME_PERIOD,
    df_input = df_inputs_raw_complete,
)

##  Instantiate some transformations. Make sure to run this cell to create the transformations folder for the first time or if you wish to overwrite

In [ ]:
# set an ouput path and instantiate
if not TRANSFORMATIONS_DIR_PATH.exists():
    trf.instantiate_default_strategy_directory(
        transformers,
        TRANSFORMATIONS_DIR_PATH,
    )
else:
    logger.info(f"Directory {TRANSFORMATIONS_DIR_PATH} already exists. Skipping instantiation.")

##  --HERE, CUSTOMIZE YOUR TRANSFORMATIONS AND STRATEGIES--

### Customizing transformations and strategies files using TransformationUtils.py classes

In [ ]:
# Generate new transformation files based on the excel mapping file. 
# Make sure to have the most updated format for the excel file, check the one used in this notebook for reference.

if ssp_transformation_cw is None:
    logger.warning("ssp_transformation_cw is not defined. Please check your config file.")
else:
    logger.info(f"Using transformation file: {ssp_transformation_cw}")
    cw_file_path = os.path.join(SCENARIO_MAPPING_DIR_PATH, ssp_transformation_cw)
    logger.info(f"Transformation file path: {cw_file_path}")
    excel_yaml_handler = TransformationYamlProcessor(scenario_mapping_excel_path=cw_file_path, yaml_dir_path=TRANSFORMATIONS_DIR_PATH)

In [ ]:
# This creates transformation yaml files for each strategy in the excel file
if ssp_transformation_cw is not None:
    logger.info("Processing YAML files...")
    excel_yaml_handler.process_yaml_files()
else:
    logger.warning("ssp_transformation_cw is not defined. Please check your config file.")

In [ ]:
# Load the transformations per strategy dictionary so we can pass it to the strategy handler
# You can also check here if the transformations in each strategy are correct

if ssp_transformation_cw is not None:
    logger.info("Loading transformations per strategy dictionary...")
    transformation_per_strategy_dict = excel_yaml_handler.get_transformations_per_strategy_dict()
    transformation_per_strategy_dict
    logger.info(f"Loaded transformations for strategies: {transformation_per_strategy_dict.keys()}")
else:
    logger.warning("No transformation handler available. Please check your config file.")

In [ ]:
# You can explore the dictionary to see the transformations per strategy
# transformation_per_strategy_dict

### Creating new strategies
- You can create new strategies from scratch.
- You can also update existing ones.

In [ ]:
# Creating new strategies by updating the strategy_definitions file.

if ssp_transformation_cw is not None:
    # You can edit this to add yours, as many as you want.
    csv_handler = StrategyCSVHandler(csv_file_path=STRATEGIES_DEFINITIONS_FILE_PATH, 
                                     yaml_dir_path=TRANSFORMATIONS_DIR_PATH, 
                                     yaml_mapping_file=STRATEGY_MAPPING_FILE_PATH, 
                                     transformation_per_strategy_dict=transformation_per_strategy_dict)

    csv_handler.add_strategy(strategy_group='PFLO', description='NDC', yaml_file_suffix='NDC')
    csv_handler.add_strategy(strategy_group='PFLO', description='NDC + Energy', yaml_file_suffix='NDC2')
    csv_handler.add_strategy(strategy_group='PFLO', description='Net Zero', yaml_file_suffix='NZ')
else:
    logger.warning("No transformation handler available. Please check your config file.")

### We finished adding new transformation files and strategies so lets load them back

In [ ]:
# then, you can load this back in after modifying (play around with it)
transformations = trf.Transformations(
    TRANSFORMATIONS_DIR_PATH,
    transformers = transformers,
)
tab = transformations.attribute_transformation.table

In [ ]:
#  build the strategies -- will export to path
t0 = time.time()
strategies = trf.Strategies(
    transformations,
    export_path = "transformations",
    prebuild = True,
)

t_elapse = sf.get_time_elapsed(t0)
logger.info(f"Strategies defined at {strategies.transformations.dir_init} initialized in {t_elapse} seconds")

In [ ]:
strategies.attribute_table

In [ ]:
# Set up the strategy codes you wish to run in ssp
strategies_to_run = [0, 6003, 6004, 6005]

##  Build our templates
- let's use the default variable groupings for LHS

In [ ]:
# Building excel templates, make sure to include the strategies ids in the strategies attribute as well as the baseline (0)
df_vargroups = _EXAMPLES("variable_trajectory_group_specification")

strategies.build_strategies_to_templates(
    # df_trajgroup = df_vargroups,
    # include_simplex_group_as_trajgroup = True,
    strategies = strategies_to_run,
)

# Finally, load SISEPUEDE so that we can run it

In [ ]:
import sisepuede as si
# timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
ssp = si.SISEPUEDE(
    "calibrated",
    db_type = "csv",
    #id_str = f"sisepuede_run_2025-07-28T12:30:52.790396",
    initialize_as_dummy = not(energy_model_flag), # no connection to Julia is initialized if set to True
    regions = [country_name],
    strategies = strategies,
    # try_exogenous_xl_types_in_variable_specification = True,
    attribute_time_period = _ATTRIBUTE_TABLE_TIME_PERIOD
)

In [ ]:
# This runs the model, make sure you edit key_stretegy with the strategy ids you want to execute include baseline (0)
dict_scens = {
    ssp.key_design: [0],
    ssp.key_future: [0],
    ssp.key_strategy: strategies_to_run,
}

ssp.project_scenarios(
    dict_scens,
    save_inputs = True,
    include_electricity_in_energy =energy_model_flag,
)

# Levers Table

In [ ]:
import sisepuede.visualization.tables as svt
tableau_levers_table = svt.LeversImplementationTable(strategies, )
tableau_levers_table_csv = tableau_levers_table.build_table_for_strategies(
    [6003, 6004, 6005]
)

In [ ]:
tableau_levers_table_csv

In [ ]:
# Read input and output files
df_out = ssp.read_output(None)
df_in = ssp.read_input(None)

In [ ]:
df_out[df_out.primary_id==0][[col for col in df_out.columns if col.startswith("prod_ippu_")]].iloc[0]

In [ ]:
df_out[df_out.primary_id==0][[col for col in df_out.columns if col.startswith("prod_ippu_")]]

In [ ]:
demand_ippu =matt.get_variable("Energy Demand by Fuel in SCOE")
demand_ippu.get_from_dataframe(df_out).iloc[35]

In [ ]:
demand_ippu =matt.get_variable("Energy Demand by Fuel in SCOE")
demand_ippu.get_from_dataframe(df_out).iloc[0]

In [ ]:
demand_ippu =matt.get_variable("Energy Demand by Fuel in SCOE")
demand_ippu.get_from_dataframe(df_out).iloc[0]

In [ ]:
frac_demand_electricity_scoe = matt.get_variable("SCOE Heat Energy Demand Scalar")
frac_demand_electricity_scoe.get_from_dataframe(df_in).head()

In [ ]:
frac_demand_electricity_scoe = matt.get_variable("SCOE Initial Per GDP Heat Energy Consumption")
frac_demand_electricity_scoe.get_from_dataframe(df_in).head()

In [ ]:
frac_demand_electricity_scoe = matt.get_variable("SCOE Initial Per GDP Electric Appliances Energy Consumption")
frac_demand_electricity_scoe.get_from_dataframe(df_in).head()

In [ ]:
frac_demand_electricity_scoe = matt.get_variable("SCOE Initial Per Household Electric Appliances Energy Consumption")
frac_demand_electricity_scoe.get_from_dataframe(df_in).head()

In [ ]:
demand_energy_tech = matt.get_variable("Energy Demand by Fuel in Energy Technology")
demand_ccsq = matt.get_variable("Energy Demand by Fuel in CCSQ")
demand_industrial_energy = matt.get_variable("Energy Demand by Fuel in Industrial Energy")
demand_scoe = matt.get_variable("Energy Demand by Fuel in SCOE")
demand_transportation = matt.get_variable("Energy Demand by Fuel in Transportation")
demand_industrial = matt.get_variable("Energy Demand in Industrial Energy")

In [ ]:
demand_scoe.get_from_dataframe(df_out).iloc[0]

In [ ]:
def plot_field_stack(
    df,
    fields,
    dict_format,
    time_col="time_period",
    primary_id=0,
    figsize=(18, 8),
    legend_loc='upper right',
    legend_bbox=(1.1, 1),
    ylabel="MT Emissions CO2e",
    xlabel="Time Period",
    title=None,
):
    """
    Plots a stack plot of the selected fields for a given primary_id.

    Args:
        df (pd.DataFrame): DataFrame containing output data.
        fields (list): List of column names to plot.
        dict_format (dict): Formatting dictionary for colors.
        time_col (str): Name of the time column.
        primary_id (int): Value of primary_id to filter.
        figsize (tuple): Figure size.
        legend_loc (str): Legend location.
        legend_bbox (tuple): Legend bbox_to_anchor.
        ylabel (str): Y-axis label.
        xlabel (str): X-axis label.
        title (str): Plot title.
    """
    fig, ax = plt.subplots(figsize=figsize)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    if title:
        ax.set_title(title)

    df_plot = df[df[ssp.key_primary].isin([primary_id])]

    fig, ax = spu.plot_stack(
        df_plot,
        fields,
        dict_formatting=dict_format,
        field_x=time_col,
        figtuple=(fig, ax),
    )

    ax.legend(loc=legend_loc, bbox_to_anchor=legend_bbox, title="Fields")
    plt.show()

In [ ]:
## Fix FGTV when having super large spikes (Only use when there are spikes)
primary_id_to_fix = 72072
df_out[df_out.primary_id==primary_id_to_fix][[col for col in df_out.columns if 'fgtv' in col]].plot(figsize=(10,5))

def hampel_clean(
    s: pd.Series,
    window: int = 7,
    n_sigmas: float = 5.0,
    strategy: str = "prev",  # "prev" | "median" | "linear" | "nan"
):
    """
    Detects spikes using a rolling median + MAD (Hampel) and replaces them.

    Returns
    -------
    cleaned : pd.Series
    mask : pd.Series[bool]  # True where a spike was found
    """
    s = s.astype(float).copy()

    # Rolling median
    med = s.rolling(window, center=True, min_periods=max(3, window//2)).median()

    # Rolling MAD (median absolute deviation)
    def _mad(x):
        m = np.median(x)
        return np.median(np.abs(x - m))
    mad = s.rolling(window, center=True, min_periods=max(3, window//2)).apply(_mad, raw=False)

    # Robust z-score using MAD (~= std when multiplied by 1.4826)
    sigma = 1.4826 * mad
    # Fallbacks at edges
    med = med.fillna(s.median())
    sigma = sigma.replace(0, np.nan).fillna(sigma[sigma>0].median() or 1.0)

    z = (s - med).abs() / sigma
    mask = z > n_sigmas  # spike locations (True = spike)

    # Impute
    cleaned = s.copy()
    if strategy == "prev":
        # copy previous *valid* value
        # (for first element or consecutive spikes, fall back to local median)
        for idx in np.where(mask)[0]:
            if idx > 0 and not np.isnan(cleaned.iloc[idx-1]):
                cleaned.iloc[idx] = cleaned.iloc[idx-1]
            else:
                cleaned.iloc[idx] = med.iloc[idx]
    elif strategy == "median":
        cleaned[mask] = med[mask]
    elif strategy == "linear":
        tmp = cleaned.copy()
        tmp[mask] = np.nan
        cleaned = tmp.interpolate(method="linear", limit_direction="both")
    elif strategy == "nan":
        cleaned[mask] = np.nan
    else:
        raise ValueError("Unknown strategy")

    return cleaned, mask

# --- Example on your Series s ---
# s_clean, spike_mask = hampel_clean(s, window=7, n_sigmas=5.0, strategy="prev")

# select the subset
subset = df_out[df_out.primary_id == primary_id_to_fix].copy()

# get only the relevant columns
cols = [c for c in df_out.columns if 'fgtv' in c]

# make a copy to store cleaned results
cleaned_subset = subset.copy()
spike_masks = {}

# apply Hampel cleaning to each relevant column
for c in cols:
    cleaned_subset[c], spike_masks[c] = hampel_clean(
        subset[c],
        window=7,
        n_sigmas=5.0,
        strategy="prev"  # or "median"/"linear"
    )

# if you want to merge back into df_out:
df_out.loc[df_out.primary_id == primary_id_to_fix, cols] = cleaned_subset[cols]
df_out[df_out.primary_id==primary_id_to_fix][[col for col in df_out.columns if 'fgtv' in col]].plot(figsize=(10,5))

In [ ]:
# Define the fields to plot and the formatting dictionary
subsector_emission_fields = matt.get_all_subsector_emission_total_fields()

dict_format = dict(
    (k, {"color": v}) for (k, v) in
    matt.get_subsector_color_map().items()
)

In [ ]:
primary_ids_to_plot = df_out[ssp.key_primary].unique()
primary_ids_to_plot

In [ ]:
# Plot the emissions stack for the primary_id 0 (which is the baseline)
for primary_id in primary_ids_to_plot:

    plot_field_stack(
        df_out,
        subsector_emission_fields,
        dict_format,
        primary_id=primary_id,
        title=f"Emissions Stack Plot for Primary ID {primary_id}"
    )

In [ ]:
df_out[df_out.primary_id==0][[col for col in df_out.columns if col.startswith("prod_ippu_metals_tonne")]]

# Export Wide File (Last Mandatory Step)

In [ ]:
all_primaries = sorted(list(df_out[ssp.key_primary].unique()))

# build if unable to simply read the data frame
if df_in is None:
    df_in = []
     
    for region in ssp.regions:
        for primary in all_primaries: 
            df_in_filt = ssp.generate_scenario_database_from_primary_key(primary)
            df_in.append(df_in_filt.get(region))
    
    df_in = pd.concat(df_in, axis = 0).reset_index(drop = True)




df_export = pd.merge(
    df_out,
    df_in,
    how = "left",
)



# check output directory 
dir_pkg = os.path.join(
    ssp.file_struct.dir_out, 
    f"sisepuede_summary_results_run_{ssp.id_fs_safe}"
)
os.makedirs(dir_pkg) if not os.path.exists(dir_pkg) else None


for tab in ["ATTRIBUTE_STRATEGY"]:
    table_df = ssp.database.db.read_table(tab)
    if table_df is not None:
        table_df.to_csv(
            os.path.join(dir_pkg, f"{tab}.csv"),
            index=None,
            encoding="UTF-8"
        )
    else:
        print(f"Warning: Table {tab} returned None.")


df_primary = (
    ssp
    .odpt_primary
    .get_indexing_dataframe(
        sorted(list(df_out[ssp.key_primary].unique()))
    )
)
    
df_primary.to_csv(
    os.path.join(dir_pkg, f"ATTRIBUTE_PRIMARY.csv"),
    index = None,
    encoding = "UTF-8"
)

df_export.to_csv(
    os.path.join(dir_pkg, f"sisepuede_results_{ssp.id_fs_safe}_WIDE_INPUTS_OUTPUTS.csv"),
    index = None,
    encoding = "UTF-8"
)

In [ ]:
# Getting the directory where the outputs are stored
ssp.file_struct.dir_out

In [ ]:
RUN_ID_OUTPUT_DIR_PATH = os.path.join(
    RUN_OUTPUT_DIR_PATH, 
    f"sisepuede_results_{ssp.id_fs_safe}"
)

os.makedirs(RUN_ID_OUTPUT_DIR_PATH, exist_ok=True)

df_primary.to_csv(
    os.path.join(RUN_ID_OUTPUT_DIR_PATH, "ATTRIBUTE_PRIMARY.csv"),
    index = None,
    encoding = "UTF-8"
)

df_export.to_csv(
    os.path.join(RUN_ID_OUTPUT_DIR_PATH, f"sisepuede_results_{ssp.id_fs_safe}_WIDE_INPUTS_OUTPUTS.csv"),
    index = None,
    encoding = "UTF-8"
)

for tab in ["ATTRIBUTE_STRATEGY"]:
    table_df = ssp.database.db.read_table(tab)
    if table_df is not None:
        table_df.to_csv(
            os.path.join(RUN_ID_OUTPUT_DIR_PATH, f"{tab}.csv"),
            index=None,
            encoding="UTF-8"
        )
    else:
        logger.warning(f"Warning: Table {tab} returned None.")

In [ ]:
tableau_levers_table_csv.to_csv(
            os.path.join(RUN_ID_OUTPUT_DIR_PATH, "tableau_levers_table.csv"),
            index=None,
            encoding="UTF-8"
        )

In [ ]:
RUN_ID_OUTPUT_DIR_PATH

In [ ]:
# gdp_df = df_in[["time_period", "gdp_mmm_usd"]].copy()
# gdp_df["year"] = gdp_df["time_period"] + 2015
# gdp_df = gdp_df.drop(columns=["time_period"])
# gdp_df.head()